server:
  port: 8084

spring:
  application:
    name: payment_service

  rabbitmq:
    addresses: ${RABBITMQ_PRIVATE_URL}

resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3

  retry:
    instances:
      productService:
        maxAttempts: 3
        waitDuration: 500ms

  timelimiter:
    instances:
      productService:
        timeoutDuration: 2s
        cancelRunningFuture: true

  bulkhead:
    instances:
      productService:
        maxConcurrentCalls: 5
        maxWaitDuration: 0

stripe:
  secret-key: ${STRIPE_SECRET_KEY}