server:
  port: 8082

spring:
  application:
    name: cart-service

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      username: ${REDIS_USER}
      password: ${REDIS_PASSWORD}
      timeout: 60000

  rabbitmq:
    addresses: ${RABBITMQ_PRIVATE_URL}
